name: Lint & Validate

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dev tools (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Lint (Black & flake8)
        run: |
          black --check .
          flake8 orchestrator

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt (check)
        working-directory: infra
        run: terraform fmt -check

      - name: Terraform validate
        working-directory: infra
        run: |
          terraform init -backend=false
          terraform validate
